# Generated by Django 2.1 on 2018-08-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is cool, too!'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='this is cool!'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='car'),
        ),
    ]
